execution_env=local
#execution_env=remote
appURL1= https://tutorialsninja.com/demo/
appURL2 = https://www.opencart.com/index.php?route=cms/demo
email= pujasoni0@gmail.com
password= puja2947
#password=pujak2947 -- to fail the logintest
searchProductName= iPhone

now load this config file in setup method
#standalone:  http://192.168.29.204:4444 - url for standalone grid testing--grid url
#hub url--http://localhost:4444/